services:
  slack_reminder:
    build: .
    env_file: .env
    command: python slack_reminder.py

  test:
    build: .
    command: python -m unittest discover -s . -p "test_*.py" -v
    environment:
      - ENV=test
      - PERSONAL_GITHUB_TOKEN=dummy_token
      - SLACK_BOT_TOKEN=dummy_token
      - SLACK_CHANNEL_ID=dummy_channel
